### ISSUE TITLE
Fails to checkout submodules

### ISSUE THREAD

**Issue by smaillet** [Mushus/checkout-submodule#1]
On "windows-latest" hosts I get the following error attempting to check out submodules:

##[error]Unable to locate executable file: C:\Program. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
##[error]Node run failed with exit code 1

**Comment by Mushus** [comment]
Thank you for your report.
Currently only supports linux. I'll do it soon.

**Comment by Mushus** [comment]
done
usage: https://github.com/Mushus/checkout-submodule/blob/master/.github/workflows/test.yml#L22-L39
